export const listEmployee=[
    {
        id:1,
        Name:'David',
        Age:20,
        projects:["Facebook","Lazada"]
    },
    {
        id:2,
        Name:'Linda',
        Age:22,
        projects:["Facebook","Shopee"]
    },
    {
        id:3,
        Name:'Kevin',
        Age:40,
        projects:["Shopee","Lazada"]
    }
]